const express = require("express")
const app = express()
const cors = require("cors")
require('dotenv').config()
app.use(cors())
app.use(express.json())
const musicRouter = require('./routes/music')
app.use("/api/v1/musics", musicRouter)
app.listen(process.env.PORT, () => console.log("Server is running on port 5000"))